dist: xenial
sudo: required
language:
- node_js
node_js:
- 'stable'
install:
- npm i -g npm
- npm i -g testcafe
cache:
  directories:
  - node_modules
addons:
  firefox: latest
  chrome: stable
  sonarcloud:
    organization: adobeinc
services:
- xvfb

jobs:
  - name: test integration env
    script:
    - npm install
    - npm run build:prod
    - npm run functional:ci
    - npm run test:saucelabs
    - npm run checkbundlesize
  - name: test production env
    script:
    - npm install
    - npm run functional:local:prod
    if: env(TRAVIS_EVENT_TYPE) = cron

notifications:
  slack: adobedx:AlI4WB2ojGDcqsBEVZ1EGsCR
  email:
  recipients:
    - mowla@adobe.com
    - khoury@adobe.com
    - aahardy@adobe.com
  on_success: always
  on_failure: always
  
before_install:
- stty cols 80

