dist: xenial
os: linux
language: node_js
node_js: 'stable'
install:
- npm i -g npm
- npm i -g testcafe
cache:
  directories:
  - node_modules
addons:
  firefox: latest
  chrome: stable
  sonarcloud:
    organization: adobeinc
services:
- xvfb

jobs:
  include:
      script:
      - npm install
      - if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then npm run functional:cron:prod; fi
      - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then npm run build:prod; fi
      - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then npm run functional:ci; fi
      - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then npm run test:saucelabs; fi
      - if [ "$TRAVIS_EVENT_TYPE" != "cron" ]; then npm run checkbundlesize; fi

notifications:
  slack: adobedx:AlI4WB2ojGDcqsBEVZ1EGsCR
  email:
  recipients:
    - mowla@adobe.com
    - khoury@adobe.com
    - aahardy@adobe.com
  on_success: always
  on_failure: always
  
before_install:
- stty cols 80
