name: Pre-Edge-Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
env:
        SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        SAUCE_CAPABILITIES_OVERRIDES_PATH: 'sauceLabsCapabilities.json'
        ALLOY_ENV: prod
        EDGE_BASE_PATH: ee-pre-prd

jobs:
  alloy-prod-e2e:
    name: "Pre Edge: Prod E2E Tests"
    runs-on: ubuntu-latest
    steps:
      name: "Alloy Int Edge Prod E2E Test"
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
        with:
          ref: "2.4.0-test"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run test:functional:build:prod
      - name: Run TestCafe Tests
        run: npm run test:functional:ci:prod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
