name: Pre-Edge-Deploy
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  get-testing-tags:
    name: Fetch releases
    runs-on: ubuntu-latest
    outputs:
      matrixInput: ${{ steps.list-tags.outputs.matrixInput }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm install @octokit/rest semver
      - name: Retrieve tags
        id: list-tags
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const getTestingTags = require('./scripts/getTestingTags.js');
            const tagsToTest = await getTestingTags();
            const matrixInput = { include: tagsToTest.map(tag => ({tag})) }
            core.setOutput("matrixInput", JSON.stringify(matrixInput[0].include)[1]);
            console.log("matrixInput: ", matrixInput);

  pre_edge_deploy:
    name: "Pre Edge: Prod E2E Tests"
    strategy:
      matrix: ${{ fromJSON(needs.get-testing-tags.outputs.matrixInput) }}
    needs: get-testing-tags
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      SAUCE_CAPABILITIES_OVERRIDES_PATH: 'sauceLabsCapabilities.json'
      SAUCE_JOB: "Konductor Pre-Edge Deploy"
      ALLOY_ENV: prod
      EDGE_BASE_PATH: ee-pre-prd
    steps:
      - name: Create a workflow dispatch event with ${{ matrix.tag }}
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ matrix.tag }}
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Get version from package
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build
        run: npm run test:functional:build:prod
      - name: Run TestCafe Tests
        run: npx testcafe -q -c 5 'saucelabs:Chrome@latest:macOS 11.00','saucelabs:IE@latest:Windows 10','saucelabs:Firefox@latest:Windows 10','saucelabs:Safari@latest:macOS 11.00'
        env:
          ALLOY_PROD_VERSION: ${{ steps.package-version.outputs.current-version }}
